image: openjdk:17

pipelines:
  default:
    - step:
        name: Test with bld
        caches:
          - maven
        script:
          - ./bld download
          - ./bld compile
          - ./bld test
