name: javadocs-pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  JDK_VERSION: "21"
  KOTLIN_VERSION: "2.3.20"

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ env.JDK_VERSION }}

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: ${{ env.KOTLIN_VERSION }}

      - name: Build GitHub Pages
        run: ./bld pages

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          # Upload generated docs repository
          path: "build/docs/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
